### ISSUE TITLE
No outup after tmole <port>

### ISSUE THREAD

**Issue by Antjrobles** [robbie-cahill/tunnelmole-client#1]
Hi, after trying in mac:
` curl -s https://tunnelmole.com/sh/install-mac.sh --output install-mac.sh && sudo bash install-mac.sh `
`tmole 3000`
with a React instance running on 192.168.0.50:3000, gets no output, stuck in `tmole 3000`.
Same in Ubuntu:
`curl -s https://tunnelmole.com/sh/install-linux.sh | sudo bash`
`tmole 3001`
running another instance of react in a different machine. Am I doing something wrong? Thanks

**Comment by doulighan** [comment]
Same here, on MacOS
```
$ which tmole
~ /usr/local/bin/tmole
$ tmole 8080
~
```

**Comment by robbie-cahill** [comment]
Thanks for reporting this.

Are your macs Intel or M1?

**Comment by doulighan** [comment]
> Thanks for reporting this.
> 
> Are your macs Intel or M1?

Intel chip for me. MacOS Big Sur 11.4, Intel i7

**Comment by CKylinMC** [comment]
Same on Windows 11 (Clink+Terminal)

**Comment by assadk88** [comment]
Experiencing the same issue on an M1

**Comment by robbie-cahill** [comment]
This is a bit of a weird one. The OP said it happens on Ubuntu, which is what I run. But heres my output for the installer, then running `tmole`.

Installing
```
➜  tunnelmole-client git:(main) curl -s https://tunnelmole.com/sh/install-linux.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.6M  100 30.6M    0     0  6474k      0  0:00:04  0:00:04 --:--:-- 6799k
  _______                     _                 _
 |__   __|                   | |               | |
    | |_   _ _ __  _ __   ___| |_ __ ___   ___ | | ___
    | | | | | '_ \| '_ \ / _ \ | '_ ` _ \ / _ \| |/ _ \
    | | |_| | | | | | | |  __/ | | | | | | (_) | |  __/
    |_|\__,_|_| |_|_| |_|\___|_|_| |_| |_|\___/|_|\___|



Congrats! tunnelmole is now installed 😃
Now what?
 - Get a random public URL for a local server: "tmole <port>" e.g. "tmole 80" if your server is running on port 80
 - Get a customized public URL for a local server: "tmole 80 as mysite.tunnelmole.com"
 - Read the docs for more detailed instructions https://tunnelmole.com/docs
```

Running
```
➜  tunnelmole-client git:(main) tmole 3000
http://zcroha-ip-157-211-195-169.tunnelmole.com is forwarding to localhost:3000
https://zcroha-ip-157-211-195-169.tunnelmole.com is forwarding to localhost:3000
```

Is there any output from the `tmole 3000` command at all?

You could also try building from source, its pretty straightforward and you only need NodeJS installed. The [README](https://github.com/robbie-cahill/tunnelmole-client/blob/main/README.md) has instructions.

**Comment by robbie-cahill** [comment]
Also curious if anything might have happened during the download.

For those getting this on Linux and Mac, can you run the following:
`md5sum /usr/local/bin/tunnelmole && ls -l /usr/local/bin/tunnelmole` (not `tmole`, its just a symlink).

What happens if you run `tmole` without any arugments?

**Comment by assadk88** [comment]
Running that I get:

```
bab625f0c50ee561309f1de1a9adc030  /usr/local/bin/tunnelmole
lrwxr-xr-x  1 root  wheel  20  3 Mar 17:20 /usr/local/bin/tunnelmole -> /usr/local/bin/tmole
```

**Comment by Antjrobles** [comment]
In my case running that I get:
```
MD5 (/usr/local/bin/tunnelmole) = bab625f0c50ee561309f1de1a9adc030
lrwxr-xr-x 20 root 28 Feb 12:05  /usr/local/bin/tunnelmole -> /usr/local/bin/tmole
```
and running `tmole` y get this:
```
Usage:

Get a random public URL: "tmole <port>"
For example you would run "tmole 80" (without the quotes) if your local server is running on port 80.
Your server will then be accessible under a random URL like https://f38fg.tmole.sh which will be shown in the output.
This method is free and is a good way to get started.

Get a public URL that does not change: "tmole <port> as <subdomain>.tmole.sh"
For example you would run "tmole 80 as myapi.tmole.sh" (without the quotes) if your server runs on port 80 and you want to make it available with the domain myapi.tmole.sh
This method requires a subscription which comes with an API key. Get one at https://dashboard.tmole.sh from $5.99 per month and support the development of this app.

Tmole.sh URLs are accessible from any unrestricted internet connection in the world. You don't need special firewall rules or network config, all traffic is routed through this client app from our servers to your local server.

More detailed instructions, cookbooks and more are available at https://tmole.sh/docs


tmole - Share your local server with a Public URL

Options:
  -V, --version           output the version number
  --set-api-key <apiKey>  Set your API key. After purchasing a subscription you can copy and paste the command
                          shown on the page
  -h, --help              display help for command
```

**Comment by robbie-cahill** [comment]
Looks like the download worked, so I'm suspecting something network or firewall related.

By default tunnelmole creates a websocket connection to  `service.tunnelmole.com` on port `8083`.

Are you behind a corporate network or firewall, or trying this from home? 

I'd like to know if you're able to connect. Can you try running the following and send me the output?
`curl https://service.tunnelmole.com:8083/`

You should get "Upgrade Required" if you were able to successfully connect.

As an example, here is what I get
```
➜  ~ curl https://service.tunnelmole.com:8083/
Upgrade Required
```

**Comment by Antjrobles** [comment]
That's correct. This is what I get:
```
curl https://service.tunnelmole.com:8083/
Upgrade Required
```
Tested on Mac.

**Comment by robbie-cahill** [comment]
Ok so you can connect, but there must be something else going on.

I've just published a new version with optional debug logging.

Could you guys run the copy/paste install code again to update, then run tunnelmole like this with the new debug option:

`tmole 3000 --debug`

Then paste the output here? This will print all Websocket messages sent/received from the client to the service and so should give some more information on what state the connection gets to before it freezes.

**Comment by robbie-cahill** [comment]
I've finally been able to reproduce this issue.

On my main fiber internet connection I wasn't getting this issue.

However, when I switched to the mobile hotspot connection on my phone I got the issue.

I've updated some config on the server side and the issue is no longer happening for me.

@Antjrobles  @assadk88  @doulighan @CKylinMC could you try again and let me know if this issue still happens?

**Comment by Antjrobles** [comment]
Hi Robbie, now works perfectly. Now running `tmole 3000` I get the output. THANKS!!

**Comment by robbie-cahill** [comment]
It turns out this was certain hostnames failing to look up, so I added code to gracefully handle this error: https://github.com/robbie-cahill/tunnelmole-service/commit/cba9d33d65f626fd6ad2975f890579f72c47a518

**Comment by sccpsteve** [comment]
I can confirm that this fix is working! Thanks for everything.

**Comment by CKylinMC** [comment]
It works fine now, thanks!!
