### ISSUE TITLE
Next.js web server unresponsive, results in 504 gateway timeout

### ISSUE THREAD

**Issue by curiousercreative** [robbie-cahill/tunnelmole-client#10]
### software versions
```
$ cat /etc/os-release
PRETTY_NAME="Pop!_OS 22.04 LTS"
$ node --version
v18.15.0
$ yarn tunnelmole -V
2.1.10
$ yarn next --version
Next.js v12.3.4
```

### repro
1. `yarn add tunnelmole`
1. `yarn next dev & yarn tunnelmole 3000`
    ER/AR: tunnel seems to work, the Next.js app loads in browser
1. `yarn build && yarn start & yarn tunnelmole 3000`
    AR: Next.js app never loads in browser, eventually 504 gateway timeout

**Comment by robbie-cahill** [comment]
This could be something to do with the lack of Websocket support. Does this work with other servers/frameworks?

**Comment by curiousercreative** [comment]
@robbie-cahill I haven't tried with other servers/frameworks, just the two servers that ship with Next.js and the results reported above. I'd bet it works with other servers and frameworks given that it works with the Next.js dev server. re: websockets, your diagram suggests my server does not participate in any websocket connection. Given there seems to be a disconnect somewhere between the tunnelmole service and Next.js server, what do you recommend for further debugging?

**Comment by robbie-cahill** [comment]
@curiousercreative I just fixed an issue where occasionally Tunnelmole was sending an invalid HTTP request. Would you be able to update to the latest version and see if you get the same issue?

**Comment by curiousercreative** [comment]
@robbie-cahill sorry for the late response, but I've just now used this app again with the latest tunnelmole and the issue does appear to be resolved. Thanks very much!
