### ISSUE TITLE
Tunnel TCP connection (so we can expose SSH)

### ISSUE THREAD

**Issue by ArielAleksandrus** [robbie-cahill/tunnelmole-client#12]
I'd like to know if it's possible to use Tunnelmole to connect to SSH. If not, I'd like to suggest this feature.

If we tunnel our port 22, we get both the http and https tunnelmole links

If we try to connect, such as with:

`ssh user@<tunnelmole url>`

We get this error:

`user@<tunnelmole url>: Permission denied (publickey)`

**Comment by robbie-cahill** [comment]
Nope, Tunnelmole only supports HTTP/HTTPs. Other protocols i.e. SSH are not supported. You might want to look into SSH  port forwarding instead: https://phoenixnap.com/kb/ssh-port-forwarding
