### ISSUE TITLE
Important 

### ISSUE THREAD

**Issue by 7054company** [robbie-cahill/tunnelmole-client#13]
It is unable to do some work compare to ngrok
1. It not able to fully server novnc from private localport to tunnelmole subdomain .
- it show the no vnc page , but when we try to move forward in it to open something then the novnc on tmole subdomin show it not connected to backed server.
- please developed that .
- where as in ngrok it will easily happend.

3. Where as ngrok do it .
4.

**Comment by 7054company** [comment]
![Screenshot_2023_0705_090637](https://github.com/robbie-cahill/tunnelmole-client/assets/34761088/b0e1e033-e9c1-4795-8134-dff582d5db77)

**Comment by robbie-cahill** [comment]
Tunnelmole tunnels http only. It does not support VNC.
