### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by PwccaCode** [robbie-cahill/tunnelmole-client#15]
is run build supposed to build the client executable?

if not what is the correct process to creating the node.exe for standalone usage

**Comment by thgh** [comment]
Run `npm link` in this repo or run `npm install -g tunnelmole` -> these commands will not create an executable, but will allow you to run `tmole 8080`, is that what you need?

**Comment by PwccaCode** [comment]
was looking for a way to build the client for selfhosting

**Comment by thgh** [comment]
Your question is not clear. Are you looking for the tunnelmole backend code? See [this repo](https://github.com/robbie-cahill/tunnelmole-client) and specifically issue https://github.com/robbie-cahill/tunnelmole-client/issues/16
