### ISSUE TITLE
Is there a way to silence logs in the Node package?

### ISSUE THREAD

**Issue by thekevinscott** [robbie-cahill/tunnelmole-client#19]
I'm starting `tunnelmole` in Node. It looks that by default it prints out the URLs to the console:

```
http://foo-ip-99-115-121-181.tunnelmole.net is forwarding to localhost:xxx
https://foo-ip-99-115-121-181.tunnelmole.net is forwarding to localhost:xxx
```

I can't find a way to silence these logs. Is there a way to silence them? I'm exploring using this in the context of CI tests, where the extra logging can become noisy and distract from diagnosing test failures.

Also, the output of `tunnelmole` appears to be the `https` url:

```
  const httpsURL = await tunnelmole({
    port: 55720
  });
```

I imagine this may be a much larger design ask, but I wonder if it would be helpful to also return the `http` link, or, failing that, simply return the non `http` portion of the URL (i.e., `foo-ip-98-116-111-185.tunnelmole.net`)

**Comment by OfficialCodinary** [comment]
Let me know if you got any way to do it, I'm also having the same issue, I wanted to save the URL in a place but i can't seem to get the URL in the code rather than in the console.

**Comment by thekevinscott** [comment]
[You can see my implementation here](https://github.com/thekevinscott/UpscalerJS/blob/main/internals/http-server/src/Tunnel.ts) (ignore the commented bits, I was evaluating alternatives but `tunnelmole` won out).

`tunnelmole` should return the [URL on startup](https://github.com/thekevinscott/UpscalerJS/blob/main/internals/http-server/src/Tunnel.ts#L54C5-L56C8). To silence the logs, [you can do this](https://github.com/thekevinscott/UpscalerJS/blob/main/internals/http-server/src/Tunnel.ts#L14).

**Comment by OfficialCodinary** [comment]
Thanks dude!

**Comment by robbie-cahill** [comment]
I just published a new version with quiet mode which should suppress these logs. To enable it set the environment variable `TUNNELMOLE_QUIET_MODE=1` somewhere in your environment.
