### ISSUE TITLE
Client keeps crashing

### ISSUE THREAD

**Issue by WisdomSky** [robbie-cahill/tunnelmole-client#24]
I'm using the npm tunnel mole [client](https://www.npmjs.com/package/@thgh/tunnelmole).

using this command:

    npm install -g @thgh/tunnelmole && npx tunnelmole --set-api-key 123456789 && npx tunnelmole 32400 as sudomain.website.com

The service I'm proxying is Plex media server. After logging into my plex media server and redirected to home page, the client will just randomly crash.

```
/usr/local/lib/node_modules/@thgh/tunnelmole/node_modules/ws/lib/sender.js:116
keen_frances-localtunnel-1  |       throw new TypeError('First argument must be a valid error code number');
keen_frances-localtunnel-1  |             ^
keen_frances-localtunnel-1  | TypeError: First argument must be a valid error code number
keen_frances-localtunnel-1  |     at Sender.close (/usr/local/lib/node_modules/@thgh/tunnelmole/node_modules/ws/lib/sender.js:116:13)
keen_frances-localtunnel-1  |     at HostipWebSocket.close (/usr/local/lib/node_modules/@thgh/tunnelmole/node_modules/ws/lib/websocket.js:287:18)
keen_frances-localtunnel-1  |     at WebSocketCloseMessage (file:///usr/local/lib/node_modules/@thgh/tunnelmole/message-handlers.ts:28:38)
keen_frances-localtunnel-1  |     at HostipWebSocket. (file:///usr/local/lib/node_modules/@thgh/tunnelmole/src/tunnelmole.ts:98:9)
keen_frances-localtunnel-1  |     at HostipWebSocket.emit (node:events:526:35)
keen_frances-localtunnel-1  |     at Receiver.receiverOnMessage (/usr/local/lib/node_modules/@thgh/tunnelmole/node_modules/ws/lib/websocket.js:1068:20)
keen_frances-localtunnel-1  |     at Receiver.emit (node:events:514:28)
keen_frances-localtunnel-1  |     at Receiver.dataMessage (/usr/local/lib/node_modules/@thgh/tunnelmole/node_modules/ws/lib/receiver.js:517:14)
keen_frances-localtunnel-1  |     at Receiver.getData (/usr/local/lib/node_modules/@thgh/tunnelmole/node_modules/ws/lib/receiver.js:435:17)
keen_frances-localtunnel-1  |     at Receiver.startLoop (/usr/local/lib/node_modules/@thgh/tunnelmole/node_modules/ws/lib/receiver.js:143:22)
```

any idea why this is happening?

**Comment by thgh** [comment]
Hmm, I have had a similar issue. It's related to websocket support. There is a case where a websocket errors or times out and that error code number is not valid when replaying it on localhost. There is no way to trigger a "fake websocket error".

I think `1006` is the problematic error code, but maybe there are others?
https://github.com/thgh/tunnelmole-client/blob/4af0c873e4e9b700db601e4b6d8b6db64f1f98ca/message-handlers.ts#L28

The `ws` package uses this function:
https://github.com/websockets/ws/blob/d8dd4852b81982fc0a6d633673968dff90985000/lib/validation.js#L35-L44

**Comment by WisdomSky** [comment]
just to add, my tunnel mole server is proxied by nginx-proxy-manager. and also enabled web socket support option in the hostname:

![image](https://github.com/robbie-cahill/tunnelmole-client/assets/6792172/82e304e9-42d8-4934-b2af-5ee7c4462bb7)

so I'm not sure if nginx-proxy-manager is also part of the cause or not.

**Comment by WisdomSky** [comment]
@thgh can I ask if this is still a recurring issue? I'd like to give tunnel mole an another shot.

**Comment by robbie-cahill** [comment]
@WisdomSky  The main module for this project is at https://www.npmjs.com/package/tunnelmole. I would suggest changing to that one (`npm install -g tunnelmole`) and see if that resolves the issue.
