### ISSUE TITLE
Python FastAPI not working

### ISSUE THREAD

**Issue by HappyGroupHub** [robbie-cahill/tunnelmole-client#26]
As the title described, the service isn't working properly.
I can't access my web service with the generated URL, it keeps showing up [504 Gateway Time-out / nginx/1.18.0 (Ubuntu)]
I just bought the Lite plan and hope this issues can be fixed soon!
Thanks~

The terminal looks fine.
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/43276256/83d4b054-e12d-439f-ae2d-eb0d4bd0efe0)
But the URL is not working.
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/43276256/3f136727-4c11-4a60-b752-478eb87220e5)

**Comment by robbie-cahill** [comment]
I just confirmed the service is up.

This might have come from your server or mine but probably means exactly what it says, there was a timeout. Perhaps your local server did not respond in time?

The other thing that can cause this is if your local server is not running or if there is some firewall blocking it. The request will eventually time out in this case.

**Comment by HappyGroupHub** [comment]
I do can access my website instantly with `localhost:5005`.
So i think the problem should be the firewalls setting maybe?

I'm using windows to host the web-app service, soI've set port 5005 TCP allowance in firewall settings
Am I doing correct? (It didn't work as well)

**Comment by HappyGroupHub** [comment]
Also, I've tested the exact same program and port with Ngrok, and it works fine.
The bot I'm trying to host is [Ethereum Wallet Tracker](https://github.com/HappyGroupHub/Ethereum-Wallet-Tracker), and i hope this helps you out.

**Comment by robbie-cahill** [comment]
What happens if you try other services/frameworks? maybe a simple web server with `serve`?https://npmjs.com/package/serve

**Comment by HappyGroupHub** [comment]
Hi Robbie,

I'm sorry I don't have much time to helping out the debug process, but I just wanna express that mine Python FastAPI app can't be served. 
I don't really know why, but it's just works fine with ngrok and Cloudflare tunnel.
I hope this issue can be figured out why soon, since a python FastAPI app is very common haha

**Comment by robbie-cahill** [comment]
Thanks, I'll set up a simple FastAPI app and see how I go.

**Comment by robbie-cahill** [comment]
@HappyGroupHub I set up my FastAPI app based on https://github.com/asdkant/fastapi-hello-world and tested it out locally.

I used the latest FastAPI version. Instead of 502 Gateway Timeout from the Tunnelmole service, I got "Invalid HTTP request" from FastAPI, which was wierd. Not sure if this is the same issue or not.

Digging further I found an issue where Tunnelmole always sends a request body even if none is sent, which was causing this error. Once I fixed that my FastAPI app worked fine.

I've just released a fix, can you update to the latest version and try again?

**Comment by HappyGroupHub** [comment]
Just tested it out again, it still didn't work as well.

But I'm a little bit confused that, did I really downloaded the latest updated version?
Cuz I found there's no Release page, instead, I downloaded the program with the [link](https://tunnelmole.com/downloads/tmole.exe) that written in README.md

**Comment by robbie-cahill** [comment]
Interesting. Since I verified things are working with the latest FastAPI version, can you tell me what version of FastAPI you are using? 

It might also be useful to see what happens if you try this on another machine, to rule out any Windows Firewall rules etc...

**Comment by HappyGroupHub** [comment]
Sorry for the late response.
The FastAPI version I'm using is `v0.104.0`

As for the other testing stuffs, I'm sorry I don't have time for those tests.
Thanks!
