### ISSUE TITLE
Hanging via CLI as well as programatically

### ISSUE THREAD

**Issue by mkurapov** [robbie-cahill/tunnelmole-client#27]
Hey @robbie-cahill ! Thank you for the library, it has been working well for us over the last several weeks. 
However, today, tunnelmole seems to be hanging via the CLI, similar to #1 :

```sh
max ~  $ tmole -V
2.2.5
max ~  $ tmole 3030
// hangs, no output
```

as well as programatically:
```js
const url = await tunnelmole({
    port: 3030
});
```
I have asked others to try it, and it is the same issue, whether that's on Linux, or Mac (M1/M2). No VPN/firewalls.

Is there a way to get debug logs to help with troubleshooting?

Thanks!

**Comment by sam-artuso** [comment]
Having the same problem.

**Comment by robbie-cahill** [comment]
Looks like I had a server issue, this is now sorted.

**Comment by mkurapov** [comment]
Thanks @robbie-cahill !
