### ISSUE TITLE
Not working in WSL

### ISSUE THREAD

**Issue by junaga** [robbie-cahill/tunnelmole-client#28]
I have `linux-x64` `node-v18.17.1` on the [Windows Subsystem for Linux version 2](https://learn.microsoft.com/en-us/windows/wsl/about)

```sh
PORT=8080 node dist/server/entry.js &
sudo npm install -g tunnelmole
tunnelmole 8080
```

I also tried `$ sudo tunnelmole 8080`, and server on `HOST=0.0.0.0` all error

```
/usr/lib/node_modules/tunnelmole/node_modules/node-fetch/lib/index.js:1501
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
          ^
FetchError: request to http://localhost:8001/tunnelmole-log-telemetry failed, reason: connect ECONNREFUSED 127.0.0.1:8001
    at ClientRequest.<anonymous> (/usr/lib/node_modules/tunnelmole/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by romualdr** [comment]
Same issue on macOS 13.6

**Comment by mahdi-above** [comment]
Did you find any solution to this?

I am using Windows 11 and see exact same error.

**Comment by junaga** [comment]
> Did you find any solution to this?
> 
> I am using Windows 11 and see exact same error.

@mahdi-above no, i used another service https://github.com/junaga/debian/blob/main/home/junaga.rc.bash#L62

**Comment by robbie-cahill** [comment]
This is the same issue as https://github.com/robbie-cahill/tunnelmole-client/issues/29.

A fix has been published, you'll need to upgrade to the latest version (2.2.9)
