### ISSUE TITLE
Tunnelmole exceeded hourly limit even though I have started the tunnel after 2 hours.

### ISSUE THREAD

**Issue by yeasir-coredevs** [robbie-cahill/tunnelmole-client#32]
I am using tunnelmole to tunnel my backend server but it is showing that I have exceeded my hourly limit where I have opened the tunnel after 2 hours for that.
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/139320574/7d857b3d-9acf-4421-8cfc-f4c1ad502fc5)

If there is any way to solve this please let me know.

**Comment by robbie-cahill** [comment]
Try now, looks like the rate limiting had a bug.

**Comment by yeasir-coredevs** [comment]
Thanks... it worked.
