### ISSUE TITLE
Post request turning into get request and many post requests are dropped

### ISSUE THREAD

**Issue by ThierryDeruyttere** [robbie-cahill/tunnelmole-client#33]
Hi,

I was observing some pretty strange behavior. All my get requests come through, but when I do a post request to a specific URL, then it also works. But the second post request to the same URL suddenly gets transformed into a get request?

**Comment by robbie-cahill** [comment]
Have not seen any other reports so will close this for now, but i'll keep an eye out for more reports that might give me a better understanding of the issue.
