### ISSUE TITLE
Certificate expired on *.tunnelmole.com

### ISSUE THREAD

**Issue by forabi** [robbie-cahill/tunnelmole-client#34]
`tmole xxxx` Fails to start because the certificate on wildcard subdomains is expired.

One of the failing URLs: `https://service.tunnelmole.com/tunnelmole-log-telemetry`

Even skipping telemetry with the env variable does not work around the issue. I guess there are other subdomains affected.

**Comment by robbie-cahill** [comment]
thanks for reporting, this should be fixed now
