### ISSUE TITLE
Can't build tunnelmode-client on Windows.

### ISSUE THREAD

**Issue by Bihari** [robbie-cahill/tunnelmole-client#36]
I am trying to build tunnelmole-service and tunnelmole-client on my local Windows Server 2022 machine. I have node 20.11.0 and TypeScript 5.3.3.

The tunnelmode-service builds without any problem. However, the tunnelmole-client fails during "npm install". I do have the latest code downloaded.  I have attached log file. Can you please help me understand what is going on?

Thanks!

[2024-01-18T19_25_08_117Z-debug-0.log](https://github.com/robbie-cahill/tunnelmole-client/files/13980889/2024-01-18T19_25_08_117Z-debug-0.log)

**Comment by robbie-cahill** [comment]
Just looking at those logs and it seems that there are some permissions issues. I'm not sure how its done, but maybe you can try making those folders full access? 
```
788 warn cleanup     'D:\\root\\tunnelmole-client-main\\node_modules\\@babel',
788 warn cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\root\tunnelmole-client-main\node_modules\@babel\generator'] {
788 warn cleanup       errno: -4048,
788 warn cleanup       code: 'EPERM',
788 warn cleanup       syscall: 'rmdir',
788 warn cleanup       path: 'D:\\root\\tunnelmole-client-main\\node_modules\\@babel\\generator'
788 warn cleanup     }
788 warn cleanup   ],
```

Not sure why it is trying to run 
```
C:\WINDOWS\system32\cmd.exe /d /s /c cjs/bin/postinstall.js
```
I have a post install script but `node` is prepended to it so `cmd` should not be trying to run it directly https://github.com/robbie-cahill/tunnelmole-client/blob/b0f452992222191219d7edf7a7ac0bdb1391e278/package.json#L47

**Comment by Bihari** [comment]
I had tried that already by granting Everyone full access to the entire folder hierarchy that contains the code being built with no difference in behavior.
