### ISSUE TITLE
Tunnel Going In And Out

### ISSUE THREAD

**Issue by LWFlouisa** [robbie-cahill/tunnelmole-client#39]
Why would I would I purchase a subscription to a permanent URL address, if I can't even rely on the trial url to not constantly reset? The entire reason to self-host is bypassing the issues inhrent to text and other media hosted here.

I basically had to upload my video here with a 25MB limit ( a limit almost all modern YT videos go past ), and then plug it into my self-hosted site.

**Comment by robbie-cahill** [comment]
I'm a bit confused as to what exactly you are referring to? Are you trying to self host your own [Tunnelmole Service](https://github.com/robbie-cahill/tunnelmole-service)?

In terms of "tunnels going in and out", I checked the service and it looks health. The service is working and all of the end to end tests are passing.

**Comment by robbie-cahill** [comment]
I'm a bit confused as to what exactly you are referring to? Are you trying to self host your own [Tunnelmole Service](https://github.com/robbie-cahill/tunnelmole-service)?

In terms of "tunnels going in and out", I checked the service and it looks healthy. The service is working and all of the end to end tests are passing.
