### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by zebleck** [robbie-cahill/tunnelmole-client#40]
When I try to expose a port I get:
504 Gateway timeout

**Comment by robbie-cahill** [comment]
seems to be working for me

**Comment by rustybrooks** [comment]
@robbie-cahill I'm also getting a 504 - it's coming from nginx so I assume that's your actual infrastructure

Oddly, it only seems to happen when I'm running my service in docker (specifically on a mac under colima).  I have noticed with this config that localhost seems... problematic and often I need to use 127.0.0.1 instead.

**Comment by rustybrooks** [comment]
> @robbie-cahill I'm also getting a 504 - it's coming from nginx so I assume that's your actual infrastructure
> 
> Oddly, it only seems to happen when I'm running my service in docker (specifically on a mac under colima). I have noticed with this config that localhost seems... problematic and often I need to use 127.0.0.1 instead.

I figured this out - colima is not exposing ports to both :1 and 127.0.0.1 - but /etc/hosts defines "localhost" as both of these.  One possible fix is to get colima to expose ports to both, but in the short term I commented out the ipv6 version of localhost, and this fixed all my localhost vs 127.0.0.1 problems, including the 504 problem noted here.
