### ISSUE TITLE
Clarify limit of connections for free tier

### ISSUE THREAD

**Issue by mkurapov** [robbie-cahill/tunnelmole-client#41]
Hi @robbie-cahill, looks like recently the limit of connections for free users has been capped at 1. Should this be clarified in the README?

**Comment by robbie-cahill** [comment]
You must be referring to concurrent connections (simultaneous connections where you are running multiple instances of the Tunnelmole client at the same time).

Its capped to one concurrent connection for free users if you are using the tunnelmole.com hosted service, so you can only run one client instance at a time as a free user. 

But you get up to 5 concurrent connections if you sign up to the Essential plan, which is $9.99 at the time of writing https://dashboard.tunnelmole.com/.

Its also possible self host your own service https://github.com/robbie-cahill/tunnelmole-service

I'll have to find the best place to add the details of the free limits again. The message does mention the limit if you try to run 2 instances of the client as a free user.
