### ISSUE TITLE
Connection Error because of certificate expired

### ISSUE THREAD

**Issue by Marius-Ruckh** [robbie-cahill/tunnelmole-client#46]
Hey,

i tried to run "tmole 3000".

I get following Error:
FetchError: request to https://service.tunnelmole.com/tunnelmole-log-telemetry failed, reason: connect ECONNREFUSED 157.245.179.192:443

If i try to call 157.245.179.192:443 in my browser i get "SSL error: certificate has expired". So my company might block because of a expired certificate.
Is there a way to fix this?

**Comment by robbie-cahill** [comment]
You had me in a bit of a panic there. The certificate expires in June so its not expired. I didn't get the same error.
