### ISSUE TITLE
Tunnel mole stuck

### ISSUE THREAD

**Issue by Yeasir-Hossain** [robbie-cahill/tunnelmole-client#47]
I am using tunnel mole to forward my server running at port 4000 but the forwarding links are not showing. Please refer to the image below. It gets stuck here.
![Screenshot from 2024-05-15 13-53-21](https://github.com/robbie-cahill/tunnelmole-client/assets/60513610/2af239fd-d963-49f9-bdd2-d875bb29d565)

**Comment by awdev1** [comment]
Same here

**Comment by adrianRodil** [comment]
I can't get it to work either

**Comment by robbie-cahill** [comment]
Not sure what happened there but I restarted the service, now the issue is fixed

**Comment by Yeasir-Hossain** [comment]
Please provide the command, not finding the service as well.

**Comment by robbie-cahill** [comment]
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/7199408/93a4a958-7ab4-46f3-9d99-5929b47dc599)
its back to working, usual commands should work.

**Comment by Yeasir-Hossain** [comment]
Thanks.Its working perfectly.

**Comment by awdev1** [comment]
Workin here!

**Comment by Eleiber** [comment]
Hi! The same issue is happening again. Tried from my own computer and also a remote server.
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/13054092/7bbdd977-cbc0-4de9-8d34-52d79b0ccdd8)

**Comment by siscia** [comment]
I really appreciate this project. But I have to report the same issue.

@robbie-cahill
