### ISSUE TITLE
Tunnelmole showing opened multiple connections but there is no open connection

### ISSUE THREAD

**Issue by Yeasir-Hossain** [robbie-cahill/tunnelmole-client#48]
I am trying to open a tunneling url I have no opened ports but it is showing that I have already opened one port. I have also checked if tunnelmole process is running or not.
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/60513610/2b220970-b14e-42da-892c-1aea729ab0af)

**Comment by robbie-cahill** [comment]
What I would try here is `killall tunnelmole`, that should remove any redundant tunnels. If it does not work immediately try again in an hour or so for all the connection handles to clean themselves up.

**Comment by Yeasir-Hossain** [comment]
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/60513610/e1630e4c-a581-4076-af6b-605bfaa23f7a)
Please check the above screenshot. I already have tried what you said.

**Comment by robbie-cahill** [comment]
I don't have windows so might be hard to test this. 

Next time it happens can either of you run `tasklist` in a terminal then paste the output here? Just to make sure there are no zombie processes running.

**Comment by Yeasir-Hossain** [comment]
My problem fixed on its own after 3/4 days on ubuntu.
