### ISSUE TITLE
Cant connect with Home Assistant via Tunnelmole

### ISSUE THREAD

**Issue by EmielvanBeek** [robbie-cahill/tunnelmole-client#52]
I cant connect to my home assistant system that is connected via a tunnelmole client.
I get constantly the following screen.
![daa0d7e25005eba8ca2747d339628da302fcaa64](https://github.com/user-attachments/assets/cbe366a3-c02a-4944-b128-d7635621f9ba)

When i connect my HA instance directly via a ip address then it works but not via tunnelmole what i want to give it a bit of security.
i got login errors in my logs when i login into HA when i connect via Tunnelmole.

**Comment by robbie-cahill** [comment]
Most likely it has a TCP based protocol that is not HTTP/HTTPs. Tunnelmole currently only supports services running over HTTP/HTTPs.
