### ISSUE TITLE
Cannot run tunnelmole

### ISSUE THREAD

**Issue by chaslain** [robbie-cahill/tunnelmole-client#53]
Despite having no tunnels open, no instances of tunnel mole running on the computer, after restarting, and after reinstalling tunnel mole, I am getting this message at every run:

```

Hey there 👋 

It looks like you're liking Tunnelmole enough that you've tried to scale things up by opening more than one connection simultaneously - fantastic!

However, as a free user, you are currently limited to one connection at a time. But, we have a solution! Our paid plans offer the freedom of multiple concurrent connections - simply perfect for your needs.

Explore our range of plans and boost your productivity by keeping multiple connections active all at once.

Ready to upgrade your user experience and streamline your workflows? Visit https://t.ly/TrtJz
```

Please either provide a way to downgrade, provide a way to cancel the tunnel from the server side, or some other way to rectify the situation.

**Comment by chaslain** [comment]
Temporarily circumvented by dropping to version 2.0
(I assume)
curl https://install.tunnelmole.com/n20d0/install && sudo bash install

**Comment by robbie-cahill** [comment]
You could potentially have stale connections on the server side. In which case, waiting one hour will clear them out so you can try again.
