### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by IsusRamzy** [robbie-cahill/tunnelmole-client#54]
Running it and using the URL tells me `504 Gateway Time-out` .  
Do I need to change firewall settings?
OS:  Fedora 40
Tested Server: Flask Starter with `app.run(host='0.0.0.0')`

(btw, I recommend using Debian for your servers)

**Comment by robbie-cahill** [comment]
Usually this means either your server is not running over HTTP or HTTPs, or there is no port open on the port you are forwarding to.

**Comment by IsusRamzy** [comment]
> Usually this means either your server is not running over HTTP or HTTPs, or there is no port open on the port you are forwarding to.

It's running on HTTP, an I'm using the correct port.

**Comment by IsusRamzy** [comment]
@robbie-cahill
