### ISSUE TITLE
TypeError on Run

### ISSUE THREAD

**Issue by GoAwayNow** [robbie-cahill/tunnelmole-client#6]
I installed tunnelmole via NPM and get this error every time I try to run it.

```
TypeError: program.name(...).usage is not a function
    at run (file:///C:/Users/user/AppData/Roaming/npm/node_modules/tunnelmole/bin/tunnelmole.ts:29:10)
    at file:///C:/Users/user/AppData/Roaming/npm/node_modules/tunnelmole/bin/tunnelmole.ts:56:11
    at file:///C:/Users/user/AppData/Roaming/npm/node_modules/tunnelmole/bin/tunnelmole.ts:57:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

I have Node v19.8.1 and NPM 9.6.4.

**Comment by robbie-cahill** [comment]
I just set up Node v19.8.1, I didn't get this error.

```
➜  tunnelmole-client git:(main) node --version
v19.8.1
➜  tunnelmole-client git:(main) tmole 3000
http://yl04rp-ip-157-211-195-169.tunnelmole.com is forwarding to localhost:3000
https://yl04rp-ip-157-211-195-169.tunnelmole.com is forwarding to localhost:3000
```

How exactly are you running it?

**Comment by GoAwayNow** [comment]
Nothing out of the ordinary as far as I know. I had only just installed
Node via winget, then I updated NPM, then installed tunnelmole with the
command in the readme. Then I just typed "tmole <port>" with, of course, an
actual port, I just can't remember the specific port right now.

**Comment by GoAwayNow** [comment]
Oh, yeah, Windows 10 Pro 22H2, Powershell 7.3.3.

**Comment by robbie-cahill** [comment]
I'd try getting node from the offical site https://nodejs.org, maybe something is going on with the winget version.
