### ISSUE TITLE
ARM support ?

### ISSUE THREAD

**Issue by d8570c6827e5ee3ebb03d92b0c464782** [robbie-cahill/tunnelmole-client#7]
Hello:) Trying to run tunnelmole on a Jetson Nano Developper Kit running Ubuntu 18.04. Seems to be because binary is compiled for x86 and no binary is provided for ARM. Could it ?

Getting the following error : 
```
user@pathtoserver:/usr/local/bin$ tmole 8888
-bash: /usr/local/bin/tmole: cannot execute binary file: Exec format error
```

**Comment by robbie-cahill** [comment]
There is no binary from arm.

But you should be able to do is just install tunnelmole using npm `npm install -g tunnelmole`
