### ISSUE TITLE
npm i -g tunnelmole not working on windows

### ISSUE THREAD

**Issue by RayyanNafees** [robbie-cahill/tunnelmole-client#9]
# Tried via pnpm
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/59685062/0a6f0e00-ba14-4df2-948a-adfade95e305)

# Tried via npm
![image](https://github.com/robbie-cahill/tunnelmole-client/assets/59685062/f1184916-a947-455c-a694-90804e6e1ac7)

> is there any npx script available to run ? as in...
`pnpm dlx tmole` or `npx tmole`

**Comment by robbie-cahill** [comment]
Looks like a permissions issue. Any way to run this in a terminal you opened as an Administrator?

**Comment by RayyanNafees** [comment]
> Looks like a permissions issue. Any way to run this in a terminal you opened as an Administrator?

This is Admin Terminal... I tried chmod +x flags too but...

**Comment by Alynntheyelloweyed** [comment]
I'm having the same issues. Most of the permissions errors were really because those folders they were trying to rmdir didn't exist, so I slowly added those folders which eliminated all those errors, just leaving one

```npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm ERR! code 1
npm ERR! path F:\Local Documents\Documents\VisualStudioCodeProjects\FG Twitch Extension Server\node_modules\tunnelmole
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cjs/bin/postinstall.js
npm ERR! 'cjs' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in: C:\Users\Alynn\AppData\Local\npm-cache\_logs\2023-06-04T16_20_46_971Z-debug-0.log```

tunneling is the last part of this section of this project

**Comment by sk-tjdownes** [comment]
Can confirm, broken on Windows 11, using nvm. Similar errors to above.

To me, it appears that the path to `cjs` is incorrect, even though it's definitely installed.

**Comment by robbie-cahill** [comment]
I wonder if its because of the script being like
```
"postinstall": "cjs/bin/postinstall.js"
```

That works fine on Linux (which I run as my main driver), because the script has this shebang at the top of it. I guess windows does not recognize that?
```
#!/usr/bin/env node
```

I've just published a new version which changes the script to explicitly invoke node.
```
"postinstall": "node cjs/bin/postinstall.js"
```

I don't have Windows installed to test however. Would one of you be able to test with the latest version `2.1.11`?

https://github.com/robbie-cahill/tunnelmole-client/commit/8311e9c6f2e45b8af5c765f3878682fb10656249

**Comment by sk-tjdownes** [comment]
yup. that seems to resolve the issue. `npm install tunnelmole` works perfectly fine on Windows 11. Thanks for the fast resolution!

**Comment by robbie-cahill** [comment]
Excellent, i'll close the issue
